name: jaguar_recaptcha
description: reCAPTCHA server side support Dart and Jaguar.dart
version: 0.0.3
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_recaptcha
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar_client: ^0.1.2
  jaguar_serializer: ^0.3.10
  jaguar: ^0.6.5

dev_dependencies:
  test: ^0.12.0
