name: jaguar_recaptcha
description: reCAPTCHA server side support Dart and Jaguar.dart
version: 1.2.1
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_recaptcha
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar_client: ^0.2.1
  jaguar_serializer: ^0.5.1
  jaguar: ^1.2.6
  http: ^0.11.3+16
  date_format: ^1.0.2

dev_dependencies:
  test: ^0.12.0
